from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path

from quant_eam.data_lake.demo_ingest import main as demo_ingest_main
from quant_eam.data_lake.lake import DataLake
from quant_eam.datacatalog.catalog import DataCatalog


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def test_demo_ingest_is_reproducible(tmp_path: Path, monkeypatch) -> None:
    # Make created_at deterministic for the manifest.
    monkeypatch.setenv("EAM_DATA_ROOT", str(tmp_path))
    monkeypatch.setenv("SOURCE_DATE_EPOCH", "1700000000")

    snap = "snap_repro_001"
    assert demo_ingest_main(["--snapshot-id", snap]) == 0

    lake = DataLake(root=tmp_path)
    data_path = lake.dataset_csv_path(snap, "ohlcv_1d")
    manifest_path = lake.manifest_path(snap)
    h1 = (_sha256(data_path), _sha256(manifest_path))

    # Run again with same inputs -> identical outputs.
    assert demo_ingest_main(["--snapshot-id", snap]) == 0
    h2 = (_sha256(data_path), _sha256(manifest_path))
    assert h1 == h2


def test_asof_filter_excludes_future_available_at(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.setenv("EAM_DATA_ROOT", str(tmp_path))
    monkeypatch.setenv("SOURCE_DATE_EPOCH", "1700000000")

    snap = "snap_asof_001"
    assert demo_ingest_main(["--snapshot-id", snap]) == 0

    cat = DataCatalog(root=tmp_path)
    # dt is daily anchored at 16:00+08:00. At midnight, the same day bar is not yet available.
    rows, stats = cat.query_ohlcv(
        snapshot_id=snap,
        symbols=["AAA", "BBB"],
        start="2024-01-01",
        end="2024-01-10",
        as_of="2024-01-05T00:00:00+08:00",
    )
    assert stats.rows_before_asof > stats.rows_after_asof
    assert len(rows) == stats.rows_after_asof


def test_available_at_autogenerated_from_policy(tmp_path: Path, monkeypatch) -> None:
    monkeypatch.setenv("EAM_DATA_ROOT", str(tmp_path))
    monkeypatch.setenv("SOURCE_DATE_EPOCH", "1700000000")

    lake = DataLake(root=tmp_path)
    snap = "snap_gen_av_001"

    # Provide rows without available_at -> DataLake must fill it deterministically.
    rows = [
        {
            "symbol": "AAA",
            "dt": "2024-01-01",
            "open": 100,
            "high": 101,
            "low": 99,
            "close": 100.5,
            "volume": 1000,
        }
    ]
    manifest = lake.write_ohlcv_1d_snapshot(snapshot_id=snap, rows=rows)
    ds = manifest["datasets"][0]
    assert ds["extensions"]["available_at_strategy"] == "policy_default_latency"

    # Query at a time before the bar close (16:00) should return 0.
    cat = DataCatalog(root=tmp_path)
    out, stats = cat.query_ohlcv(
        snapshot_id=snap,
        symbols=["AAA"],
        start="2024-01-01",
        end="2024-01-01",
        as_of="2024-01-01T12:00:00+08:00",
    )
    assert stats.rows_before_asof == 1
    assert stats.rows_after_asof == 0
    assert out == []

